### ISSUE TITLE
가위바위보

### ISSUE THREAD

**Issue by kangsLee** [qkraudghgh/9xd-bot#3]
게임 추가!

**Comment by qkraudghgh** [comment]
최근에 일이 바빠 제대로 확인하지 못했네요 ㅎㅎ 요번 연휴내에 추가하겠습니다!

**Comment by kangsLee** [comment]
정말로 추가되는건가요! ㅎㅎ

**Comment by kangsLee** [comment]
아직도 안됐어 이놈의 가위바위보

**Comment by qkraudghgh** [comment]
마음이 닫지 않는 기능은 개발하기가 쉽지 않네요 마음이 동하면 개발하겠습니다 ㅎㅎㅎ
