### ISSUE TITLE
Hubot heroku keep alive 관련 이슈

### ISSUE THREAD

**Issue by myungseokang** [qkraudghgh/9xd-bot#62]
Keep alive 기능으로 New relic 을 사용한다고 들었는데, 관련해서 좋은 아이디어가 있어서 이슈 남깁니다.
https://devcenter.heroku.com/articles/scheduler
https://github.com/hubot-scripts/hubot-heroku-keepalive
두 개를 이용해서 좀 더 깔끔하게 처리할 수 있는 방법을 찾았습니다.
`hubot-heroku-keepalive` 와 `Heroku Scheduler`를 이용해서 10분마다 `curl ${HUBOT_HEROKU_KEEPALIVE_URL}heroku/keepalive` 라는 커맨드를 보내게끔 설정해주는 것입니다.
이슈 확인하시고 코멘트 남겨주시면 감사하겠습니다.

**Comment by qkraudghgh** [comment]
네 사실 다를건 없지만 우리 9xd hubot은 여러분의 기여를 더 중요시하기 때문에 PR날려주시면 당장 뉴렐릭을 때려치우겠습니다. @Leop0ld

**Comment by myungseokang** [comment]
곧 해서 올리겠습니다

**Comment by myungseokang** [comment]
관련해서는 Heroku 설정이 들어가기 때문에 새터장에서 직접 말씀드리겠습니다.
